enabled=false
max_file_bytes=1048576
allowed_prefix=/data/adb/box_bll
allowed_prefix=/data/adb/box
allowed_prefix=/data/clash
allowed_prefix=/data/media/0/Android/Clash
# file=/data/adb/box_bll/clash/config.yaml
