http:
  address: 127.0.0.1:3000
users: []
dns:
  bind_hosts:
    - 127.0.0.1
  port: 5591
  upstream_dns:
    - https://dns.example/dns-query
  ratelimit: 0
filtering:
  protection_enabled: true
  filtering_enabled: true
filters:
  - enabled: true
    url: https://anti-ad.net/easylist.txt
    name: anti-AD (AdGuard)
    id: 10001
