enabled=false
max_backup_bytes=10485760
max_file_bytes=10485760
target_manifest=targets/file-ad-targets.conf
rules_url=https://raw.githubusercontent.com/snowzlmbot/AdGuardHome-Android-Module/6f6b2ef17c14289e99cb64095c260f3fa06ea60b/module/targets/file-ad-targets.conf
rules_sha256_url=https://raw.githubusercontent.com/snowzlmbot/AdGuardHome-Android-Module/6f6b2ef17c14289e99cb64095c260f3fa06ea60b/module/targets/file-ad-targets.conf.sha256
