enabled=false
max_backup_bytes=10485760
max_file_bytes=10485760
target_manifest=targets/file-ad-targets.conf
rules_url=https://raw.githubusercontent.com/snowzlmbot/AdGuardHome-Android-Module/main/module/targets/file-ad-targets.conf
rules_sha256_url=https://raw.githubusercontent.com/snowzlmbot/AdGuardHome-Android-Module/main/module/targets/file-ad-targets.conf.sha256
