# 1=LAN-compatible, 2=encrypted-upstream, 3=bootstrap domain upstream
mode=2
I_network=0
Lock_sleep=0
port_testing=1
redirect_ipv4_dns=true
redirect_ipv6_dns=true
block_ipv4_dot=true
block_ipv6_dot=true
block_ipv4_doq=true
block_ipv6_doq=true
bypass_vpn_dns=true
bypass_vpn_encrypted_dns=true
bypass_vpn_traffic=true
lan_dns_target=
bootstrap_dns=
